### ISSUE TITLE
Display the full scale name in the content box, rather than the word 'Scale'

### ISSUE THREAD

**Issue by whitep4nth3r** [whitep4nth3r/fretonator#78]
The content/information box is so far away from the selected mode chips that people may lose the context of what mode they're jamming to when they scroll down. Can we add in the full scale name at the top left of the content box in place of the word 'scale'?

![image](https://user-images.githubusercontent.com/52798353/98041958-a029a980-1e1a-11eb-85a3-c20b90030334.png)

**Comment by lavabyrd** [comment]
Sounds like a Wednesday plan for me!
