### ISSUE TITLE
'Random mode' button

### ISSUE THREAD

**Issue by whitep4nth3r** [whitep4nth3r/fretonator#79]
It might be fun to include a 'Random mode' button somewhere on the page, so people can discover modes they've never picked before at the press of a button.

**Comment by justinhhorner** [comment]
This sounds like fun. 🙂

What are your thoughts on this design? I tried to introduce as minimal change as possible, while still allowing for randomizing notes and modes individually. (We can find/create a more detailed icon if necessary).

<img width="805" alt="Screen Shot 2021-09-13 at 7 09 51 AM" src="https://user-images.githubusercontent.com/4635843/133074483-d17647d0-4d90-4e7e-820a-8e534dd3b642.png">

**Comment by whitep4nth3r** [comment]
Hey Justin!

I wonder whether there should be one clear button to shuffle both the key and the mode?

It should probably go above 'check out the fretboard' so the story goes...

1. Choose a starting note
2. Pick a mode
3. Or get a random one

When I got the email when you replied to this issue, I had NO IDEA what the little die meant :D And also it would have a11y implications on mobile, even if you added a tooltip or whatever.

What do you think?

**Comment by justinhhorner** [comment]
Ah, I really like your idea of adding "Or get a random one" instead of the icon. I'm also a fan of easily shuffling both the key and mode this way.

Thank you for the feedback!
