### ISSUE TITLE
[Feature] Metronome

### ISSUE THREAD

**Issue by justinhhorner** [whitep4nth3r/fretonator#86]
Looking for feedback on a new feature! 🎸

What if we had a simple metronome to use while practicing? Having one built-into the app would eliminate the need to use a separate app on mobile.

Thoughts?

**Comment by whitep4nth3r** [comment]
Love this idea!

**Comment by justinhhorner** [comment]
Awesome! Here's a mockup of a potential design for larger resolutions for both light and dark themes. I'd love to get your thoughts on it when you have the chance.

Thanks!
<img width="978" alt="fretonator-metronome-mocks" src="https://user-images.githubusercontent.com/4635843/134822174-f6b0e161-6d50-43c6-a433-70af7f54cb45.png">

**Comment by whitep4nth3r** [comment]
That's pretty nice Justin! 

My suggestions are 

- add a title to the area perhaps? Just "metronome" is fine OR it could follow the same cadence as all the titles further up the page ... I have no clue right now 🤣
- I know the thing works primarily with a slider, but I'd like to see the plus and minus buttons bigger - at least 44 x 44px for a11y
- do we need a "bpm" anywhere? 
- what about time signatures and providing a different sound on the first beat of the bar? Is that overkill?

**Comment by justinhhorner** [comment]
Thank you!

- What about a title like "Stay in time" or "Practice to a click"? For now, I'm using "Metronome".
- Agree 💯. I've adjusted the size of those buttons.
- Added "bpm".
- Maybe we keep those features in mind and add them if we get requests to add more beyond the initial release. What do you think?


<img width="978" alt="fretonator-metronome-mocks_02" src="https://user-images.githubusercontent.com/4635843/134825906-8a1a860b-7a6f-4877-a9a0-245b2bfea079.png">

**Comment by whitep4nth3r** [comment]
I think I like 'Stay in time' — let's see how that works.

Love the additions, let's gooo!
