### ISSUE TITLE
Time for a job update ❤️ 

### ISSUE THREAD

**Issue by CrisFavero** [whitep4nth3r/fretonator#89]
https://github.com/whitep4nth3r/fretonator/blob/0cd0b0dc7dcc0545456173616a055e77e802d506/apps/fretonator-web/src/app/common/footer/footer.component.html#L62

**Comment by whitep4nth3r** [comment]
You're correct! I've actually got a branch in progress that cleans a lot of things up... but I'm having some issues with nx... it's in progress and thank you!
