### ISSUE TITLE
How do I integrate it into the website?

### ISSUE THREAD

**Issue by iemecen** [whitep4nth3r/fretonator#96]
I prepared the files with the ng build command.
When I throw the files in the dist folder to the hosting side, a white screen appears.

**Comment by lavabyrd** [comment]
so, what exactly are you trying to achieve by integrating it @iemecen ? Do you just want to host your own version of this or do you want to integrate part of it onto your site? If this is an existing site (https://muzikveyasam.com for example?), you're gonna have problems as you're using a wordpress site and this is a stand alone app/site. Can you tell us a bit more about what you are actually trying to do?

**Comment by iemecen** [comment]
Yes, I want to run it as a separate page within the existing wordpress site.
Of course, it is not integrated into wordpress.
I want to link to the index.html file by running it in a separate folder on the host.

I extracted the project files to the dist folder with ng build.
It didn't happen.

There is no problem working on localhost.

But the files in the dist folder give a white screen.

**Comment by whitep4nth3r** [comment]
If you're able to share the logs on the production server, that would help someone diagnose what's going wrong on production, given it works on localhost. 

I'm not very familiar with WordPress and how WordPress hosting handles serving a bunch of static files, so I'm lost too. 

This project isn't currently built to be able to bundle, install and run on other websites, so I'm not sure I'll be able to help you. The code is open source in order for people to experiment with – not to provide the code in bundles bespoke to people's specific requirements. 

If you'd like to [join our Discord](https://discord.gg/theclaw) maybe you can talk through the problem in the tech help channel or the fretonator channel. 

Good luck!

**Comment by iemecen** [comment]
Considering that I don't know about software, then it seems like I can't do it without support from someone who knows.

Thank you all.

The project was exactly what I was looking for.
